export const romanMap = {
    'あ': 'a',
    'い': 'i',
    'う': 'u',
    'え': 'e',
    'お': 'o',
    'か': 'ka',
    'き': 'ki',
    'く': { inputOne: 'ku', inputTwo: 'cu' },
    'け': 'ke',
    'こ': { inputOne: 'ko', inputTwo: 'co' },
    'さ': 'sa',
    'し': 'si',
    'す': 'su',
    'せ': 'se',
    'そ': 'so',
    'た': 'ta',
    'ち': 'ti',
    'つ': 'tu',
    'て': 'te',
    'と': 'to',
    'な': 'na',
    'に': 'ni',
    'ぬ': 'nu',
    'ね': 'ne',
    'の': 'no',
    'は': 'ha',
    'ひ': 'hi',
    'ふ': { inputOne: 'fu', inputTwo: 'hu' },
    'へ': 'he',
    'ほ': 'ho',
    'ま': 'ma',
    'み': 'mi',
    'む': 'mu',
    'め': 'me',
    'も': 'mo',
    'や': 'ya',
    'ゆ': 'yu',
    'よ': 'yo',
    'ら': 'ra',
    'り': 'ri',
    'る': 'ru',
    'れ': 're',
    'ろ': 'ro',
    'わ': 'wa',
    'ゐ': 'wi',
    'ゑ': 'we',
    'を': 'wo',
    'ん': { inputOne: 'nn', inputTwo: 'xn' },
    'が': 'ga',
    'ぎ': 'gi',
    'ぐ': 'gu',
    'げ': 'ge',
    'ご': 'go',
    'ざ': 'za',
    'じ': { inputOne: 'ji', inputTwo: 'zi' },
    'ず': 'zu',
    'ぜ': 'ze',
    'ぞ': 'zo',
    'だ': 'da',
    'ぢ': { inputOne: 'ji', inputTwo: 'di' },
    'づ': { inputOne: 'zu', inputTwo: 'du' },
    'で': 'de',
    'ど': 'do',
    'ば': 'ba',
    'び': 'bi',
    'ぶ': 'bu',
    'べ': 'be',
    'ぼ': 'bo',
    'ぱ': 'pa',
    'ぴ': 'pi',
    'ぷ': 'pu',
    'ぺ': 'pe',
    'ぽ': 'po',
    'きゃ': 'kya',
    'きぃ': 'kyi',
    'きゅ': 'kyu',
    'きぇ': 'kye',
    'きょ': 'kyo',
    'くぁ': 'qa',
    'くぃ': 'qi',
    'くぇ': 'qe',
    'くぉ': 'qo',
    'くゃ': 'qya',
    'くゅ': 'qyu',
    'くょ': 'qyo',
    'しゃ': { inputOne: 'sha', inputTwo: 'sya' },
    'しぃ': 'syi',
    'しゅ': { inputOne: 'shu', inputTwo: 'syu' },
    'しぇ': 'she',
    'しょ': { inputOne: 'sho', inputTwo: 'syo' },
    'ちゃ': { inputOne: 'cha', inputTwo: 'tya' },
    'ちぃ': 'tyi',
    'ちゅ': { inputOne: 'chu', inputTwo: 'tyu' },
    'ちぇ': 'tye',
    'ちょ': { inputOne: 'cho', inputTwo: 'tyo' },
    'てゃ': 'tha',
    'てぃ': 'thi',
    'てゅ': 'thu',
    'てぇ': 'the',
    'てょ': 'tho',
    'ひゃ': 'hya',
    'ひぃ': 'hyi',
    'ひゅ': 'hyu',
    'ひぇ': 'hye',
    'ひょ': 'hyo',
    'ふぁ': 'fa',
    'ふぃ': 'fi',
    'ふぇ': 'fe',
    'ふぉ': 'fo',
    'みゃ': 'mya',
    'みぃ': 'myi',
    'みゅ': 'myu',
    'みぇ': 'mye',
    'みょ': 'myo',
    'ヴぁ': 'va',
    'ヴぃ': 'vi',
    'ヴぇ': 've',
    'ヴぉ': 'vo',
    'ぎゃ': 'gya',
    'ぎぃ': 'gyi',
    'ぎゅ': 'gyu',
    'ぎぇ': 'gye',
    'ぎょ': 'gyo',
    'じゃ': 'ja',
    'じぃ': 'zyi',
    'じゅ': 'ju',
    'じぇ': 'zye',
    'じょ': 'jo',
    'ぢゃ': 'dya',
    'ぢぃ': 'dyi',
    'ぢゅ': 'dyu',
    'ぢぇ': 'dye',
    'ぢょ': 'dyo',
    'びゃ': 'bya',
    'びぃ': 'byi',
    'びゅ': 'byu',
    'びぇ': 'bye',
    'びょ': 'byo',
    'ぴゃ': 'pya',
    'ぴぃ': 'pyi',
    'ぴゅ': 'pyu',
    'ぴぇ': 'pye',
    'ぴょ': 'pyo',
    'ぁ': { inputOne: 'xa', inputTwo: 'la' },
    'ぃ': { inputOne: 'xi', inputTwo: 'li' },
    'ぅ': { inputOne: 'xu', inputTwo: 'lu' },
    'ぇ': { inputOne: 'xe', inputTwo: 'le' },
    'ぉ': { inputOne: 'xo', inputTwo: 'lo' },
    'ゃ': 'xya',
    'ゅ': 'xyu',
    'ょ': 'xyo',
    //'っ': { inputOne: 'fj', inputTwo: 'jf' },
    'ヴ': 'vu',
    'ー': '-',
    '、': ',',
    ',': ',',
    '。': '.',
    '！': '!',
    '？': '?',
    ' ': ' ',
    '　': '　', // 全角の空白
};