export const sentencesToBeTyped = [
    { chara: 'ユーニ', sentenceJa: 'おいノア！ランツが強い敵とやりてぇってよ！', sentence: 'おいのあ！らんつがつよいてきとやりてぇってよ！' },
    { chara: 'トライデン', sentenceJa: '男に二言はねぇが、男はおかわりをする！', sentence: 'おとこににごんはねぇが、おとこはおかわりをする！' },
    { chara: 'タイオン', sentenceJa: '僕は失望を禁じえない', sentence: 'ぼくはしつぼうをきんじえない' },
    { chara: 'タイオン', sentenceJa: '僕は感動を禁じえない', sentence: 'ぼくはかんどうをきんじえない' },
    { chara: 'ユーニ', sentenceJa: 'セナ…お前まさか 頭ん中まで筋肉になっちまったのか？', sentence: 'せな。。。おまえまさか　あたまんなかまで　きんにくになっちまったのか？' },
    { chara: 'ランツ', sentenceJa: 'あまあまういんなは買い取らねぇのか？', sentence: 'あまあまういんなはかいとらねぇのか？' },
    { chara: 'ノア', sentenceJa: '大丈夫さ 飲み込んでしまえば 大抵のものは何とかなる', sentence: 'だいじょうぶさ　のみこんでしまえば　たいていのものはなんとかなる' },
    { chara: 'ミオ', sentenceJa: '今ここにある命 君だけに背負わせはしない', sentence: 'いまここにあるいのち　きみだけにせおわせはしない' },
    //{ chara: 'リク', sentenceJa: 'おかわりはあるも？', sentence: 'おかわりはあるも？' },
    //{ chara: 'ユーニ', sentenceJa: '敵ならぶっ飛ばす！そうじゃないなら 話ぐらい聞いてやる！どうだ！', sentence: 'てきならぶっとばす！そうじゃないなら　はなしぐらいきいてやる！どうだ！' },
    //{ chara: 'ミオ', sentenceJa: '人の命を弄ぶなぁーっ！', sentence: 'ひとのいのちをもてあそぶなぁー！' },
    //{ chara: 'ランツ', sentenceJa: 'ああ 何とか五体満足みたいだぜ', sentence: 'ああなんとかごたいまんぞくみたいだぜ' },
    //{ chara: 'アシェラ', sentenceJa: '劇的に生きて激的に死ぬ それが私の望む戦場なのさ', sentence: 'げきてきにいきてげきてきにしぬ　それがわたしののぞむせんじょうなのさ' },
    //{ chara: 'エヌ', sentenceJa: '想いや夢などとというものに縋った愚か者の末路なんだよ', sentence: 'おもいやゆめなどとというものにすがった　おろかもののまつろなんだよ' },
    //{ chara: 'ゴンドウ', sentenceJa: 'お前らが作った未来に生まれてこれるなんて最高じゃねーか', sentence: 'おまえらがつくったみらいに　うまれてこれるなんて　さいこうじゃねーか' },
    //{ chara: 'セナ', sentenceJa: 'もう 一緒に筋トレできないね', sentence: 'もういっしょにきんとれできないね' },
    //{ chara: 'ランツ', sentenceJa: '死ぬ気でやんのと死ににいくのは全然違ぇよ', sentence: 'しぬきでやんのと　しににいくのはぜんぜんちげぇよ' },
    //{ chara: 'ユーニ', sentenceJa: 'よしわかった 殴る おいノア こいつ殴っていいよな！', sentence: 'よしわかったなぐる　おいのあこいつなぐっていいよな！' }
    //{ chara: 'テスト', sentenceJa: 'あ', sentence: 'あ' },
    //{ chara: 'テスト', sentenceJa: 'い', sentence: 'い' },
    //{ chara: 'テスト', sentenceJa: 'う', sentence: 'う' },
    //{ chara: 'テスト', sentenceJa: 'え', sentence: 'え' },
    //{ chara: 'テスト', sentenceJa: 'お', sentence: 'お' },
    //{ chara: 'テスト', sentenceJa: 'か', sentence: 'か' }
];